### ISSUE TITLE
Many raw data not found

### ISSUE THREAD

**Issue by chao-peng** [RaoNikitha/CAT-LM#1]
Hi, I am trying to match file pairs to original source code in the following way:

For each file pair JSON file in Dataset/TestData/RawDataOutput/python/FilePairs/, I try to load original source code and test code recorded in this JSON file. However, I got a lot of file not found errors. Some of them are listed below:

Dataset/TestData/RawData/python/Clinical-Genomics/chanjo/build/lib/chanjo/cli/base.py not found
Dataset/TestData/RawData/python/Clinical-Genomics/chanjo/build/lib/chanjo/cli/calculate.py not found
Dataset/TestData/RawData/python/GNaive/naive-rete/build/lib/rete/__init__.py not found
Dataset/TestData/RawData/python/MrYsLab/python_banyan/build/lib/python_banyan/banyan_base/banyan_base.py not found
Dataset/TestData/RawData/python/MrYsLab/python_banyan/build/lib/python_banyan/banyan_base_multi/banyan_base_multi.py not found
Dataset/TestData/RawData/python/QTodoTxt/QTodoTxt2/build/lib/qtodotxt2/lib/file.py not found
Dataset/TestData/RawData/python/QTodoTxt/QTodoTxt2/build/lib/qtodotxt2/filters_controller.py not found
Dataset/TestData/RawData/python/QTodoTxt/QTodoTxt2/build/lib/qtodotxt2/lib/__init__.py not found
Dataset/TestData/RawData/python/Quandela/Perceval/build/lib/perceval/backends/slos.py not found
Dataset/TestData/RawData/python/Quandela/Perceval/build/lib/perceval/utils/algorithms/simplification.py not found
Dataset/TestData/RawData/python/Quandela/Perceval/build/lib/perceval/algorithm/analyzer.py not found
Dataset/TestData/RawData/python/Telefonica/toolium/build/lib/toolium/pageobjects/page_object.py not found
Dataset/TestData/RawData/python/Telefonica/toolium/build/lib/toolium/driver_wrapper.py not found
Dataset/TestData/RawData/python/Telefonica/toolium/build/lib/toolium/utils/download_files.py not found
Dataset/TestData/RawData/python/Telefonica/toolium/build/lib/toolium/pageelements/page_elements.py not found
Dataset/TestData/RawData/python/Telefonica/toolium/build/lib/toolium/config_parser.py not found
Dataset/TestData/RawData/python/Telefonica/toolium/build/lib/toolium/behave/environment.py not found
Dataset/TestData/RawData/python/Telefonica/toolium/build/lib/toolium/pageelements/input_text_page_element.py not found
Dataset/TestData/RawData/python/Telefonica/toolium/build/lib/toolium/pageelements/page_element.py not found
Dataset/TestData/RawData/python/Telefonica/toolium/build/lib/toolium/utils/driver_utils.py not found
Dataset/TestData/RawData/python/Telefonica/toolium/build/lib/toolium/driver_wrappers_pool.py not found
Dataset/TestData/RawData/python/Telefonica/toolium/build/lib/toolium/config_files.py not found
Dataset/TestData/RawData/python/Telefonica/toolium/build/lib/toolium/config_driver.py not found
Dataset/TestData/RawData/python/Telefonica/toolium/build/lib/toolium/pageobjects/mobile_page_object.py not found
Dataset/TestData/RawData/python/Viber/viber-bot-python/build/lib/viberbot/api/messages/file_message.py not found
Dataset/TestData/RawData/python/Vimjas/vint/build/lib/vint/linting/config/config_file_source.py not found
Dataset/TestData/RawData/python/Vimjas/vint/build/lib/vint/ast/plugin/scope_plugin/variable_name_normalizer.py not found
Dataset/TestData/RawData/python/Vimjas/vint/build/lib/vint/ast/plugin/scope_plugin/two_way_scope_reference_attacher.py not found
Dataset/TestData/RawData/python/Vimjas/vint/build/lib/vint/linting/policy/prohibit_implicit_scope_variable.py not found
Dataset/TestData/RawData/python/Vimjas/vint/build/lib/vint/linting/policy/prohibit_unused_variable.py not found
Dataset/TestData/RawData/python/Vimjas/vint/build/lib/vint/ast/traversing.py not found
Dataset/TestData/RawData/python/Vimjas/vint/build/lib/vint/linting/policy/prohibit_implicit_scope_builtin_variable.py not found

Could you please guide me on how to extract code pairs instead of files from your dataset?

Thank you!

**Comment by RaoNikitha** [comment]
You can run the commands from the README file in the replication package on zenodo.  The specific commands you'd need to mining data from GitHub and extract the code-test file pairs (found in Training/GitHubMining) are as follows: 
1. Run `python3 gh_crawler.py` to get a list of all the python and java repositories that have a minimum of 10 stars.
2. Run `mine_code_test_pairs_java.sh` and `mine_code_test_pairs_python.sh` to mine data and extract the code-test file pairs for python and java.
3. Run `mine_testdata.sh` to mine test data for python and java.
